console.log('📋 Manual Test Instructions:')
console.log('')
console.log('1. Open http://localhost:3000/affiliate/bio')
console.log('2. Open Browser Console (F12 or Cmd+Option+I)')
console.log('3. Edit any CTA button')
console.log('4. Change font sizes:')
console.log('   - Title: XL')
console.log('   - Subtitle: Large')  
console.log('   - Button: Large')
console.log('5. Click Save')
console.log('6. Check Console Logs:')
console.log('   - "Sending CTA data" - should show titleSize: xl')
console.log('   - "CTA Save Response" - should show status: 200, ok: true')
console.log('   - "CTA Save Success" - should show updated CTA')
console.log('   - "Fetching bio page after CTA save" - should appear')
console.log('   - "Bio page refreshed!" - should appear')
console.log('   - "Bio Page Response" - should show updated ctaButtonsCount')
console.log('7. Check Live Preview:')
console.log('   - Preview should update immediately')
console.log('   - Button should appear in the preview')
console.log('8. Check Public Bio Page:')
console.log('   - Open http://localhost:3000/bio/demoaffiliate')
console.log('   - Font should be larger (XL)')
console.log('')
console.log('✅ If all logs appear and preview updates = SUCCESS')
console.log('❌ If any log missing or preview not updating = Check that specific step')
